# Generated by Django 3.0.5 on 2020-05-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ucst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=5000)),
                ('time', models.CharField(max_length=100)),
                ('admin', models.CharField(max_length=400, null=True)),
                ('leader', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
