# Generated by Django 3.0.5 on 2020-05-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_ucst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plst',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='plst',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='ucst',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='ucst',
            name='leader',
        ),
    ]
