# Generated by Django 3.0.5 on 2020-04-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anum', models.CharField(max_length=200, unique=True)),
                ('apwd', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lnum', models.CharField(max_length=200, unique=True)),
                ('lpwd', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snum', models.CharField(max_length=200, unique=True)),
                ('spwd', models.CharField(max_length=200)),
            ],
        ),
    ]
