# Generated by Django 3.0.5 on 2020-05-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='apwd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='anum',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='leader',
            old_name='lpwd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='leader',
            old_name='lnum',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='spwd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='snum',
            new_name='userid',
        ),
    ]
