# Generated by Django 3.0.5 on 2020-06-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20200501_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='logintime',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
