# Generated by Django 3.0.5 on 2020-06-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20200603_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='jointime',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
