# Generated by Django 3.0.5 on 2020-06-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_student_jointime'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='jointime',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='logintime',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='jointime',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='logintime',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
